添加了一个ddloo的简单导航页
trickyEdecay/zero-soft-studio-general pull request #25
Opened 2019-04-17 14:22 UTC by ddloo

2019-04-17 14:23 UTC, ddloo commented
添加一个导航页

2019-04-19 13:02 UTC, GranzonLin commented
同学，页面的命名不正确哦~

2019-04-20 11:03 UTC, ddloo commented
@GranzonLin

2019-04-26 07:49 UTC, trickyEdecay requested changes
你可能不太明白作业的要求，就是 navigation 要保持和图纸的设计一致，方便后续工作的开展

2019-04-26 07:49 UTC, trickyEdecay commented on html-css/ddloo/ddloo_navigation/navigation-flex.html
> +<!DOCTYPE html>
这个不对吧？和设计图纸完全不一样呢？

<img width="693" alt="图片" src="https://user-images.githubusercontent.com/7637349/56791873-c2f8fc00-683a-11e9-9130-5c2f22c8474e.png">

2019-05-06 16:18 UTC, ddloo commented
更新了导航页、登录页面，添加了打怪兽、navigation-js页面

2019-05-24 07:18 UTC, merged