添加 Track小怪物小游戏
trickyEdecay/zero-soft-studio-general pull request #43
Opened 2019-04-23 14:01 UTC by TrackAir

2019-04-24 08:32 UTC, trickyEdecay commented
你的 `monster` 作业应该放在你自己的文件夹里面

2019-04-24 13:42 UTC, TrackAir commented
@trickyEdecay 已经将monster放到自己文件夹里面

2019-04-25 14:00 UTC, trickyEdecay requested changes
有几个大问题：
1. 变量名无论如何不要用拼音
2.标签属性和标签属性之间要留空格，养成好习惯
3. font-family 需要设置默认值

2019-04-25 14:00 UTC, trickyEdecay commented on monster-js/Track/monster.html
> +            <div class="monster-blood"id="MonsterHp">
多个属性之间应该保持一个空格，养成好习惯哈！下文也是

还有，id不要使用驼峰命名法，建议更改为 `monster-hp`

2019-04-25 14:00 UTC, trickyEdecay commented on monster-js/Track/js.js
> +    hp-=10;
这里应该加上一个判断，判断当hp小于0时的情况。

2019-04-25 14:00 UTC, trickyEdecay commented on monster-js/Track/js.js
> +var monatweHpEle=document.getElementById("MonsterHp");
`monatweHpEle` 和 `myBtnEle` 两个变量在下文没用到？

2019-04-25 14:00 UTC, trickyEdecay commented on html-css/Track/导航页flex/navigation-flex.html
> +            <div class="sousuoqi">
我发现你这里有两行 `sousuoqi` ，这个逻辑不对哈，你应该尝试着，所有的八个导航按钮都放在同一个 `sousuoqi` 的标签里面

2019-04-25 14:00 UTC, trickyEdecay commented on html-css/Track/导航页flex/navigation-flex.html
> +    <link rel="stylesheet"type="text/css"href="index.css">
```suggestion
    <link rel="stylesheet" href="index.css">
```

2019-04-25 14:00 UTC, trickyEdecay commented on html-css/Track/导航页/navigation.html
> +                    <div class="container1">
我建议把 `container1` 这个类设置到这外层的 a 标签上，然后不要掉这个 div 。不需要包多一层。

你现在使用的 a 标签导致了有一条小黑线出现
<img width="820" alt="图片" src="https://user-images.githubusercontent.com/7637349/56740908-68ad5c00-67a4-11e9-9490-9a08f68ac366.png">
这是因为 a 标签自带下划线。所以你还需要将它去掉 `text-decoration:none`

2019-04-25 14:00 UTC, trickyEdecay commented on html-css/Track/导航页/navigation.html
> +    <div class="Interface">
不要使用大写字母

2019-04-25 14:00 UTC, trickyEdecay commented on html-css/Track/导航页/index.css
> +    width: 310px;
觉得是不是少了 `box-sizing:border-box`

2019-04-25 14:00 UTC, trickyEdecay commented on html-css/Track/导航页/index.css
> +    display: inline-block;
这两个 inline-block 中间的空格没有消除，还有建议把他们设置成 `vertical-align:top`

2019-04-25 14:00 UTC, trickyEdecay commented on html-css/Track/导航页/navigation.html
> +                        <p>微博</p>
```suggestion
                        <h2>微博</h2>
```
这里使用 h2 标签，下面的描述使用 p 标签

2019-04-25 14:00 UTC, trickyEdecay commented on html-css/Track/导航页/index.css
> +    height: 1080px;
不要去设置整个页面的宽高，这个类不要了

2019-04-25 14:00 UTC, trickyEdecay commented on html-css/Track/导航页/index.css
> +    margin-left: 310px;
```suggestion
    margin-left:auto;
    margin-right:auto;
```

2019-04-25 14:00 UTC, trickyEdecay commented on html-css/Track/导航页/index.css
> +    padding-top: 160px;
```suggestion
    margin-top: 160px;
```

2019-04-25 14:00 UTC, trickyEdecay commented on html-css/Track/导航页flex/navigation-flex.html
> +<!DOCTYPE html>
这个页面好像和图纸看起来差很远？

<img width="1161" alt="图片" src="https://user-images.githubusercontent.com/7637349/56741025-a9a57080-67a4-11e9-8449-3c7bd79e8555.png">

1. **我的收藏**那几个字应该和第一个导航块对齐
2. 图标的颜色应该是白色的
3. 每个导航块的文字都不应该有下划线

2019-04-25 14:00 UTC, trickyEdecay commented on html-css/Track/login/login.html
> +<!DOCTYPE html>
这个页面存在的问题：
1. body 的 margin 没有消除
2. 输入框的样式和图纸不太一样
3. 输入框的左右留白不一样长？
<img width="507" alt="图片" src="https://user-images.githubusercontent.com/7637349/56741265-1b7dba00-67a5-11e9-981e-e0d1a3b83c57.png">

2019-04-25 14:00 UTC, trickyEdecay commented on html-css/Track/login/login.html
> +                <div id="welcome">欢迎登陆本系统</div><!--欢迎-->
```suggestion
                <h1 id="welcome">欢迎登陆本系统</h1><!--欢迎-->
```

2019-04-25 14:00 UTC, trickyEdecay commented on html-css/Track/login/login.html
> +    <link rel="stylesheet"type="text/css"href="login%20index.css">
```suggestion
    <link rel="stylesheet" href="login/index.css">
```

2019-04-25 14:00 UTC, trickyEdecay commented on html-css/Track/login/login index.css
> +}/*设置页面大小：1920*1080，背景颜色蓝色，使界面上下对齐*/
最好这样写注释：写在上面，独占一行：
```css
/*设置页面大小：1920*1080，背景颜色蓝色，使界面上下对齐*/
#yemian{
    width: 1920px;
    height: 1080px;
    background-color: blue;
    padding-bottom: 50%;
    padding-top: 50%;
    padding-top: 50px;
}
```

2019-04-26 06:21 UTC, TrackAir commented
@trickyEdecay 修改网页BUG

2019-04-26 06:45 UTC, trickyEdecay approved these changes
我又看了一下你的导航页和monster，里面还是有很多问题没修复

2019-04-26 06:45 UTC, trickyEdecay commented on html-css/Track/login/login.html
> +    <link rel="stylesheet"type="text/css"href="loginIndex.css">
文件名最好不要大写

2019-04-26 06:45 UTC, trickyEdecay commented on html-css/Track/login/login.html
>      <div id="yemian">
`yemian` 改成 `main` ？

2019-04-26 06:45 UTC, trickyEdecay commented on html-css/Track/login/login.html
>                  <input class="input"type="text"name="User" placeholder="请输入你的用户名" >
```html
<input class="input" type="text" name="user" placeholder="请输入你的用户名" >
```
属性和属性之间最好用空格隔开，然后 name 里面不要出现大写

2019-04-26 06:45 UTC, trickyEdecay commented on html-css/Track/导航页/index.css
> +    padding: 20px;
你这里设置了 padding 之后，整个 div 就变成了 350px 了
所以还要加多一个 `box-sizing:border-box`

2019-04-26 06:45 UTC, trickyEdecay commented on html-css/Track/导航页/navigation.html
> +                </a>
这些代码的标签没对齐！太乱了，然后建议改成
```html
<a href="https://www.baidu.com/" class="container1">
    <div class="left">
        <div class="yuan">
        <img class="picture" src="baidu.png">
        </div>
    </div>

    <div class="right">
        <p>百度</p>
        <div class="describe">百度，全球最大的中文搜索引擎、最大的中文</div>
    </div>
</a>
```

简而言之就是把 container1 那个 div 去掉，直接在 a 标签上设置。a 标签还需要设置一个 `text-decoration:none` 来消除掉那个黑线。
<img width="605" alt="图片" src="https://user-images.githubusercontent.com/7637349/56788301-a99f8200-6831-11e9-9aaf-c7a888d42099.png">

2019-04-26 06:45 UTC, trickyEdecay commented on html-css/Track/导航页/navigation.html
> +<!DOCTYPE html>
这个页面还是存在各种没对齐的问题

<img width="1372" alt="图片" src="https://user-images.githubusercontent.com/7637349/56787960-ae176b00-6830-11e9-842a-121fceab2cfb.png">

2019-04-26 06:45 UTC, trickyEdecay commented on monster-js/Track/monster.html
> +        <div class="attack" onclick="hello()" id="button">
这个方法改一下名字，叫做 `attack()`

2019-04-26 06:45 UTC, trickyEdecay commented on monster-js/Track/js.js
> +        return 0;
```suggestion
        hp = 0;
```

2019-04-26 06:45 UTC, trickyEdecay commented on monster-js/Track/js.js
> +var monatweHpEle=document.getElementById("monster-hp");
你这里已经取得了元素并且存在了变量里面 `monatweHpEle`。为什么下文不直接
```js
monatweHpEle.style.width=hp+"%";
```

2019-04-26 06:45 UTC, trickyEdecay commented on monster-js/Track/js.js
> +var monatweHpEle=document.getElementById("monster-hp");
而且那个 myBtnEle 是没用到的，那就把它删除掉吧~

2019-04-26 06:45 UTC, trickyEdecay commented on html-css/Track/斗鱼页面/新建文本文档.txt
> +.Header-logo{
这个文件是什么？

2019-04-26 12:02 UTC, TrackAir commented
@trickyEdecay 修改问题

2019-04-27 16:16 UTC, merged