更新登陆页
trickyEdecay/zero-soft-studio-general pull request #44
Opened 2019-04-23 14:26 UTC by HedgehogLai

2019-04-25 08:27 UTC, trickyEdecay requested changes
大概问题：

1. 布局存在不合理的地方
2. 代码文件的 tab 没有认真进行对齐
3. font-family 没有默认设置 ，例如提供一个 `sans-serif`

2019-04-25 08:27 UTC, trickyEdecay commented on html-css/HedgehogLai/login.css
> +	background: blue;
颜色是不是没按照图纸的来呀，好刺眼

2019-04-25 08:27 UTC, trickyEdecay commented on html-css/HedgehogLai/login.html
> +       	              <div class="container-top-logo">
我觉得 `<div class="container-top-logo">` 外面不用再包一层  `<div  class="container-top">`

2019-04-25 08:27 UTC, trickyEdecay commented on html-css/HedgehogLai/login.html
> +                      <p>欢迎登录本系统</p>
```suggestion
                      <h1>欢迎登录本系统</h1>
```
还有这个元素的css，它距离上面那个logo的距离你设置的是 `padding`，我建议改成 `margin`，毕竟是对外部元素之间的距离嘛~

2019-04-25 08:27 UTC, trickyEdecay commented on html-css/HedgehogLai/login.html
> +                <div class="container-button">
其实我觉得这下面也没必要包起来 `<div class="container-button">`

2019-04-25 08:27 UTC, trickyEdecay commented on html-css/HedgehogLai/login.html
> +<link rel="stylesheet" href="login.css" >
tab 没对齐

2019-04-25 08:27 UTC, trickyEdecay commented on html-css/HedgehogLai/login.html
> +                      <p class="second">登录</p>
```suggestion
                      <button class="second">登录</button>
```
按钮不要用 p 标签

2019-04-25 08:27 UTC, trickyEdecay commented on html-css/HedgehogLai/login.html
> +                      <p>注册新账号</p>
注册新账号这一块歪了
![图片](https://user-images.githubusercontent.com/7637349/56721093-c1660000-6776-11e9-8e05-882a99f9da27.png)

2019-04-25 08:27 UTC, trickyEdecay commented on html-css/HedgehogLai/login.html
> +                      <p>注册新账号</p>
建议忘记密码和注册新账号两个按钮使用 a 标签

2019-05-11 06:39 UTC, HedgehogLai commented
更新小怪兽和导航页-js

2019-05-24 07:21 UTC, merged